#- This Source Code Form is subject to the terms of the Mozilla Public
#- License, v. 2.0. If a copy of the MPL was not distributed with this
#- file, You can obtain one at http://mozilla.org/MPL/2.0/.

require "rubygems"
require "bundler"
require "rails"

Bundler.require(:default, :development) if defined?(Bundler)

Combustion.path = "./"
Combustion.initialize!

Combustion::Application.load_tasks
